language: cpp
matrix:
  include:
    - os: linux
      distro: bionic
      compiler:
        - gcc
      script:
        - make all
    - os: linux
      distro: bionic
      compiler:
        - clang
      env:
        - CXXFLAGS="-Wno-c++11-narrowing"
      script:
        - make all
    - os: windows
      before_install:
        - choco install visualstudio2019community
        - choco install visualstudio2019-workload-nativedesktop
        - echo choco install visualstudio2019-workload-vctools
        - echo cat 'C:\ProgramData\chocolatey\logs\chocolatey.log' || echo hej
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - echo $PATH
        - echo find 'c:\Program Files (x86)\Microsoft Visual Studio\2019' -name *Microsoft.Cpp.Default.props*
        - echo ls "$MSBUILD_PATH"
        - msbuild.exe cpp/vc/Radia.sln //p:Configuration=Release //p:Platform=x64
